# Configuration file for AppVeyor continuous integration on Windows
# adapted from MDTraj project (http://mdtraj.org/)

os: Windows Server 2012

environment:
  matrix: 
    - python_ver: "2.6"
      deps: "cython matplotlib numpy scipy six networkx nose setuptools pip PIL"
    - python_ver: "2.7"
      deps: "cython matplotlib numpy scipy six networkx nose setuptools pip PIL"
    #- python_ver: "3.3"
    #- python_ver: "3.4"

install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:\get-pip.py')
  - C:\Python27\python.exe c:\get-pip.py
  - C:\Python27\Scripts\pip.exe install pyyaml
  - C:\Python27\Scripts\pip.exe install pycosat
  - C:\Python27\Scripts\pip.exe install conda
  - C:\Python27\Scripts\conda.exe init
  - C:\Python27\Scripts\conda.exe update conda --yes --quiet
  - C:\Python27\Scripts\conda.exe create -n build_env --yes --quiet python=%python_ver% %deps%   
  - dir C:\Python27\envs\build_env\Scripts\
  - C:\Python27\envs\build_env\Scripts\pip.exe install wheel
  - C:\Python27\envs\build_env\python.exe setup.py bdist_wheel bdist_wininst

build_script:
    - C:\Python27\envs\build_env\Scripts\pip.exe install --pre --no-index --find-links dist/ scikit-image

test_script:
  - SET PATH=%PATH%;C:\Python27\envs\build_env\Scripts
  - cd C:\ 
  - C:\Python27\envs\build_env\Scripts\nosetests --exe -v skimage
  # The line below is being used to allow tests to run on all Python versions
  # even when the tests fail.
  #- C:\Python27\envs\build_env\Scripts\nosetests --exe -v skimage || EXIT /B 0

artifacts:
  - path: dist\*
